FROM quay.io/fedora/fedora:43

ENV LIBGUESTFS_BACKEND=direct

RUN dnf install -yq \
        curl \
        findutils \
        libvirt-daemon-config-network \
        libvirt-daemon-kvm \
        qemu-kvm \
        rsync \
        tmt+provision-virtual \
        wget2-wget \
    && dnf clean all

COPY images/fedora-43-kab.x86_64.qcow2 /opt/kab/images/fedora-43-kab.x86_64.qcow2
